### ISSUE TITLE
Please do not use blanks in file names

### ISSUE THREAD

**Issue by probonopd** [spooknik/Photopea-Appimage#1]
Please do not use blanks in file names. Please use `_` instead.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1127

**Comment by spooknik** [comment]
Thanks for the tip! It's now solved. I'm using electron-builder and it generates an AppImage with spaces for some reason. Not sure how I can specify the output file name.

**Comment by probonopd** [comment]
Thank you very much. I will put the AppImage through our automated test.

By the way:
It is best practice to upload binaries to https://github.com/spooknik/Photopea-Appimage/releases rather than putting them into the git repository. For more information, please see https://help.github.com/articles/creating-releases/.

**Comment by spooknik** [comment]
Please let me know the results of the automated test. 

I've updated and made a release for 1.1.0. :+1:

**Comment by probonopd** [comment]
Getting only a white screen when not connected to the internet:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/983b9665c9080bbe9338ac85dfb73ce393fe1f0e/database/Photopea/screenshot.png)

**Comment by spooknik** [comment]
I'll look into it!

**Comment by spooknik** [comment]
Added a notification if the app is launched without internet connectivity. This suits the app best because it can still work fine if its been cached (loaded once before) and doesn't hinder the user if that's the case. 


![screenshot from 2019-01-13 16-31-22](https://user-images.githubusercontent.com/40317809/51087229-c3203080-1750-11e9-885f-a90482b69c24.png)

**Comment by probonopd** [comment]
Thank you very much.
